import { Property } from '@/types/property';

export const FALLBACK_PROPERTIES: Property[] = [
  {
    id: 'fallback-1',
    slug: 'casa-exclusiva-lo-curro',
    title: 'Moderna Casa Mediterránea en Lo Curro',
    operation: 'venta',
    type: 'casa',
    status: 'disponible',
    priceCLP: 1850000000,
    priceUF: 48500,
    bedrooms: 5,
    bathrooms: 6,
    areaConstruida: 520,
    areaTerreno: 1400,
    address: 'Vía Roja, Lo Curro',
    comuna: 'Vitacura',
    region: 'Metropolitana',
    description: 'Espectacular casa mediterránea con vista despejada de Santiago. Finas terminaciones, gran piscina, quincho techado, quincho secundario, sala de cine, sauna y calefacción central.',
    mainImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80'
    ],
    isFeatured: true,
    isPublished: true,
    agentName: 'Sofía Valdés',
    createdAt: new Date().toISOString()
  },
  {
    id: 'fallback-2',
    slug: 'depto-las-condes-premium',
    title: 'Penthouse de Lujo en El Golf',
    operation: 'venta',
    type: 'departamento',
    status: 'disponible',
    priceCLP: 980000000,
    priceUF: 26000,
    bedrooms: 3,
    bathrooms: 4,
    areaConstruida: 240,
    areaTerreno: 240,
    address: 'Isidora Goyenechea, El Golf',
    comuna: 'Las Condes',
    region: 'Metropolitana',
    description: 'Penthouse de lujo con ascensor directo al departamento. Terrazas panorámicas, jacuzzi privado, cocina de diseño italiana integrada, 3 estacionamientos subterráneos y bodega de gran tamaño.',
    mainImage: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80'
    ],
    isFeatured: true,
    isPublished: true,
    agentName: 'Cristóbal Vial',
    createdAt: new Date().toISOString()
  },
  {
    id: 'fallback-3',
    slug: 'casa-la-dehesa-familiar',
    title: 'Hermosa Casa Familiar en Condominio La Dehesa',
    operation: 'venta',
    type: 'casa',
    status: 'disponible',
    priceCLP: 680000000,
    priceUF: 18000,
    bedrooms: 4,
    bathrooms: 3,
    areaConstruida: 210,
    areaTerreno: 450,
    address: 'El Rodeo, La Dehesa',
    comuna: 'Lo Barnechea',
    region: 'Metropolitana',
    description: 'Impecable casa familiar dentro de condominio de alta seguridad. Jardín formado con piscina climatizada, amplio quincho, logia cerrada, calefacción por radiadores, ventanas termopanel.',
    mainImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    images: [],
    isFeatured: true,
    isPublished: true,
    agentName: 'Sofía Valdés',
    createdAt: new Date().toISOString()
  },
  {
    id: 'fallback-4',
    slug: 'arriendo-departamento-providencia',
    title: 'Moderno Departamento a Pasos del Metro Tobalaba',
    operation: 'arriendo',
    type: 'departamento',
    status: 'disponible',
    priceCLP: 850000,
    priceUF: 23,
    bedrooms: 1,
    bathrooms: 1,
    areaConstruida: 55,
    areaTerreno: 55,
    address: 'Hernando de Aguirre, Providencia',
    comuna: 'Providencia',
    region: 'Metropolitana',
    description: 'Luminoso departamento de un dormitorio en suite, cocina americana equipada, closet empotrado, terraza con malla de seguridad. Edificio cuenta con piscina en la azotea, lavandería y conserjería 24/7.',
    mainImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    images: [],
    isFeatured: false,
    isPublished: true,
    agentName: 'Cristóbal Vial',
    createdAt: new Date().toISOString()
  }
];
